# -*- coding: utf-8 -*-
"""LR and RF | ML models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19RGgeSMgNf_H_QiL4El8JYsc2eX5_i3o

# **First ML project**

## **Data Loading**
"""

import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/delaney_solubility_with_descriptors.csv')
df

"""#**Data Preperation**

##Data seperation as X and Y
"""

y = df['logS']
y

x = df.drop('logS',axis =1) # axis=1 too read it in the column format
x

"""## Data Splitting

"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=100)

"""#**Model Building**

##**Linear Regression Model**

### Training the model
"""

from sklearn.linear_model import LinearRegression

lr=LinearRegression()
lr.fit(x_train,y_train)

"""###Applying the model to make prediction"""

#lr is the algorithm used here that is Linear regression
y_lr_train_pred = lr.predict(x_train)
y_lr_test_pred = lr.predict(x_test)

print(y_lr_train_pred,y_lr_test_pred)

"""###**Evaluating Model Performance**"""

from sklearn.metrics import mean_squared_error,r2_score

lr_train_mse = mean_squared_error(y_train,y_lr_train_pred)
lr_train_r2 = r2_score(y_train,y_lr_train_pred)

lr_test_mse = mean_squared_error(y_test,y_lr_test_pred)
lr_test_r2 = r2_score(y_test,y_lr_test_pred)

print('LR MSE (TRAIN):',lr_train_mse)
print('LR R2 (TRAIN):',lr_train_r2)
print('LR MSE (TEST):',lr_test_mse)
print('LR R2 (TEST):',lr_test_r2)

lr_results = pd.DataFrame(['Linear regression',lr_train_mse,lr_train_r2,lr_test_mse,lr_test_r2]).transpose()
lr_results.columns = ['Method','Training MSE','Training R2','Testing MSE','Testing R2']

lr_results

"""##**Random Forest Model**

---

###Training the model
"""

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=2,random_state=100)
rf.fit(x_train,y_train)

"""###Applying the model to make prediction"""

y_rf_train_pred = rf.predict(x_train)
y_rf_test_pred = rf.predict(x_test)

"""###Evaluating Model Performance"""

from sklearn.metrics import mean_squared_error,r2_score

rf_train_mse = mean_squared_error(y_train,y_rf_train_pred)
rf_train_r2 = r2_score(y_train,y_rf_train_pred)

rf_test_mse = mean_squared_error(y_test,y_rf_test_pred)
rf_test_r2 = r2_score(y_test,y_rf_test_pred)

rf_results = pd.DataFrame(['Random Forest',rf_train_mse,rf_train_r2,rf_test_mse,rf_test_r2]).transpose()
rf_results.columns = ['Method','Training MSE','Training R2','Testing MSE','Testing R2']
rf_results

"""## **Model Comparison**"""

df_models = pd.concat([lr_results,rf_results],axis=0)
df_models

df_models.reset_index()

"""#**Data Visualization of Predicted Results**"""

import matplotlib.pyplot as plt

plt.scatter(x=y_train,y=y_lr_train_pred ,alpha=0.3)
plt.xlabel('Experimental Logs')
plt.ylabel('Predicted Logs')
plt.grid()
plt.show()